// <auto-generated />
using System;
using ClinicApp.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("data")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicApp.Infrastructure.Persistance.DataModels.DoctorDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Major")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("Doctors", "data");
                });

            modelBuilder.Entity("ClinicApp.Infrastructure.Persistance.DataModels.PatientDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Patients", "data");
                });

            modelBuilder.Entity("ClinicApp.Infrastructure.Persistance.DataModels.RoomDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Rooms", "data");
                });

            modelBuilder.Entity("ClinicApp.Infrastructure.Persistance.DataModels.SessionDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<byte>("SessionStatus")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RoomId");

                    b.ToTable("Sessions", "data");
                });

            modelBuilder.Entity("ClinicApp.Infrastructure.Persistance.DataModels.DoctorDataModel", b =>
                {
                    b.HasOne("ClinicApp.Infrastructure.Persistance.DataModels.RoomDataModel", "Room")
                        .WithOne("Docotor")
                        .HasForeignKey("ClinicApp.Infrastructure.Persistance.DataModels.DoctorDataModel", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ClinicApp.Domain.DoctorAgg.WorkingTime", "WorkingTime", b1 =>
                        {
                            b1.Property<Guid>("DoctorDataModelId")
                                .HasColumnType("uuid");

                            b1.Property<byte>("WorkingDays")
                                .HasColumnType("smallint")
                                .HasColumnName("WorkingDays");

                            b1.HasKey("DoctorDataModelId");

                            b1.ToTable("Doctors", "data");

                            b1.WithOwner()
                                .HasForeignKey("DoctorDataModelId");

                            b1.OwnsMany("ClinicApp.Domain.DoctorAgg.TimeOff", "TimesOff", b2 =>
                                {
                                    b2.Property<Guid>("DoctorId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTimeOffset>("StartDate")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTimeOffset>("EndDate")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("reason")
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)");

                                    b2.HasKey("DoctorId", "StartDate", "EndDate");

                                    b2.ToTable("Doctor_TimesOff", "data");

                                    b2.WithOwner()
                                        .HasForeignKey("DoctorId");
                                });

                            b1.OwnsOne("ClinicApp.Domain.DoctorAgg.WorkingHours", "WorkingHours", b2 =>
                                {
                                    b2.Property<Guid>("WorkingTimeDoctorDataModelId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeOnly>("EndTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("EndTime");

                                    b2.Property<TimeOnly>("StartTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("StartTime");

                                    b2.Property<string>("TimeZoneId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("WorkingTimeDoctorDataModelId");

                                    b2.ToTable("Doctors", "data");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkingTimeDoctorDataModelId");
                                });

                            b1.Navigation("TimesOff");

                            b1.Navigation("WorkingHours")
                                .IsRequired();
                        });

                    b.Navigation("Room");

                    b.Navigation("WorkingTime")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicApp.Infrastructure.Persistance.DataModels.SessionDataModel", b =>
                {
                    b.HasOne("ClinicApp.Infrastructure.Persistance.DataModels.DoctorDataModel", "Doctor")
                        .WithMany("Sessions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicApp.Infrastructure.Persistance.DataModels.PatientDataModel", "Patient")
                        .WithMany("Sessions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("ClinicApp.Infrastructure.Persistance.DataModels.RoomDataModel", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ClinicApp.Domain.Common.ValueObjects.TimeRange", "SessionDate", b1 =>
                        {
                            b1.Property<Guid>("SessionDataModelId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("EndTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Endtime");

                            b1.Property<DateTimeOffset>("StartTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("StartTime");

                            b1.HasKey("SessionDataModelId");

                            b1.ToTable("Sessions", "data");

                            b1.WithOwner()
                                .HasForeignKey("SessionDataModelId");
                        });

                    b.OwnsOne("ClinicApp.Domain.SessionAgg.SessionDescription", "SessionDescription", b1 =>
                        {
                            b1.Property<Guid>("SessionDataModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("content")
                                .HasColumnType("text")
                                .HasColumnName("Content");

                            b1.HasKey("SessionDataModelId");

                            b1.ToTable("Sessions", "data");

                            b1.WithOwner()
                                .HasForeignKey("SessionDataModelId");
                        });

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Room");

                    b.Navigation("SessionDate")
                        .IsRequired();

                    b.Navigation("SessionDescription")
                        .IsRequired();
                });

            modelBuilder.Entity("ClinicApp.Infrastructure.Persistance.DataModels.DoctorDataModel", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ClinicApp.Infrastructure.Persistance.DataModels.PatientDataModel", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ClinicApp.Infrastructure.Persistance.DataModels.RoomDataModel", b =>
                {
                    b.Navigation("Docotor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
